models:
  'Custom Forest Detection Model': 
    'tag': 'Custom Forest Detection Model'
    'class': 'investigations.forest_investigation_class.ForestInvestigation'
    'path': 'models/checkpoints/wc_tropical_forest_best_cp.pth'

  'NDVI Calculation':
    'tag': 'NDVI Calculation'
    'class': 'investigations.ndvi_investigation_class.NDVIInvestigation'




placeholder_image_path: 'investigations/placeholder.jpg'
allowed_origins: [
  # Public
    "https://will-mckinnon.com",
    "https://www.will-mckinnon.com",
    "https://verdant.will-mckinnon.com",
    "https://www.verdant.will-mckinnon.com",

    #Local
    "http://localhost:3000",
]