name: geo-env
channels:
  - conda-forge
dependencies:
  - pandas
  - python=3.11
  - pympler
  - shapely
  - torchvision
  - matplotlib
  - torchaudio
  - pip
  - pytorch
  - pyproj
  - rasterio
  - geopandas
  - notebook
  - odc-stac
  - dask
  - ipykernel
  - xarray
  - rioxarray
  - pillow
  - pyyaml
  - tk
  - fastapi
  - uvicorn

